sudo: false
dist: trusty

language: python

python:
- '3.6'

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install ."
  - "pip install -r requirements.txt"
  - "python -c 'import nltk; nltk.download('stopwords')"

# command to run tests
script: nosetests
