sudo: false
dist: bionic

language: python

python:
- '3.7'

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install ."
  - "pip install -r requirements.txt"
  - "python -m nltk.downloader stopwords"

# command to run tests
script: nosetests
